export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_INFO = 'CHANGE_INFO';
export const CHANGE_ARTICLES = 'CHANGE_ARTICLES';
export const CHANGE_COLLECT = 'CHANGE_COLLECT';
export const CHANGE_DATA_CENTER = 'CHANGE_DATA_CENTER';
export const CHANGE_RECORD = 'CHANGE_RECORD';